# Generated by Django 3.1.1 on 2020-12-19 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0002_auto_20201219_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='text',
        ),
    ]
